#!/bin/bash

echo
echo "*************************************************"
echo "This script sets up a new development enviroment!"
echo "*************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
   exit
fi
echo

echo "Creating virtual enviroment (venv) ..."
virtualenv -p python3 venv --always-copy
echo "Done"

echo "Activating virtual enviroment (venv) ..."
source venv/bin/activate
echo "Done"

echo "Upgrading pip ..."
pip install --upgrade pip
echo "Done"

echo "Installing prerequisites ..."
pip install -r requirements.txt
echo "Done"

echo "Importing initial-data ..."
mkdir -p data
python manage.py migrate --settings=config.settings.local
python manage.py loaddata config/fixtures/superuser.json --settings=config.settings.local 
echo "Done"

echo "Environment Ready!"
echo

# 2017.08.16-DEA
