#!/bin/bash

echo
echo "************************************************"
echo "This script sets up a new production enviroment!"
echo "************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
   exit
fi
echo

read -p "Are you sure? (type production to continue) "
if [ "$REPLY" != "production" ]; then
   exit
fi
echo

echo "Pulling most recent ..."
git pull
echo "Done"

echo "Creating virtual enviroment (venv) ..."
virtualenv --python=python3 venv
echo "Done"

echo "Activating virtual enviroment (venv) ..."
source venv/bin/activate
echo "Done"

echo "Upgrading pip ..."
pip install --upgrade pip
echo "Done"

echo "Installing prerequisites ..."
pip install -r requirements.txt
echo "Done"

echo "Applying migrations ..."
mkdir -p data
python manage.py migrate --settings=config.settings.prod
echo "Done"

echo "Collecting static files ..."
mkdir -p static
mkdir -p media
python manage.py collectstatic --clear --noinput --settings=config.settings.prod
python manage.py collectstatic --noinput --settings=config.settings.prod
echo "Done"

echo "Setting permissions ..."
sudo chgrp www-data -R data/ media/
chmod 664 data/*
chmod 775 data
chmod 755 media
echo "Done"

echo "Environment Ready!"
echo

# 2017.10.02-DEA
