#!/bin/bash

echo
echo "*************************************************"
echo "This script sets up a new development enviroment!"
echo "*************************************************"
echo

read -p "Are you sure you want to continue? (yes/no) "
if [ "$REPLY" != "yes" ]; then
   exit
fi
echo

echo "Creating virtual enviroment (venv) ..."
virtualenv --python=python3 ~/venv
echo "Done"

echo "Activating virtual enviroment (venv) ..."
source ~/venv/bin/activate
echo "Done"

echo "Upgrading pip ..."
pip install --upgrade pip
echo "Done"

echo "Installing prerequisites ..."
pip install -r requirements.txt
echo "Done"

echo "Importing data ..."
mkdir -p data
python manage.py migrate
python manage.py loaddata config/fixtures/superuser.json
echo "Done"

echo "Environment Ready!"
echo

# 2017.11.01-DEA
