# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('location', models.CharField(db_column='LOCATION', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('class_field', models.CharField(blank=True, db_column='CLASS', max_length=30, null=True)),
                ('latitude', models.TextField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.TextField(blank=True, db_column='LONGITUDE', null=True)),
                ('map', models.CharField(blank=True, db_column='MAP', max_length=30, null=True)),
                ('elev', models.TextField(blank=True, db_column='ELEV', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'FEATURES',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('genus', models.CharField(blank=True, db_column='GENUS', max_length=30, null=True)),
                ('species', models.CharField(blank=True, db_column='SPECIES', max_length=30, null=True)),
                ('comname', models.CharField(db_column='COMNAME', max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'FLOWERS',
            },
        ),
        migrations.CreateModel(
            name='Sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=30, null=True)),
                ('person', models.CharField(blank=True, db_column='PERSON', max_length=30, null=True)),
                ('location', models.CharField(blank=True, db_column='LOCATION', max_length=30, null=True)),
                ('sighted', models.DateField(blank=True, db_column='SIGHTED', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'SIGHTINGS',
            },
        ),
    ]
