# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sightings',
            options={'managed': True},
        ),
    ]
